#!/bin/bash

echo "
{
  \"capabilities\": [
    {
      \"browserName\": \"*googlechrome\",
      \"maxInstances\": $MAX_INSTANCES,
      \"seleniumProtocol\": \"Selenium\"
    },
    {
      \"browserName\": \"chrome\",
      \"maxInstances\": $MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    }
  ],
  \"configuration\": {
    \"proxy\": \"org.openqa.grid.selenium.proxy.DefaultRemoteProxy\",
    \"maxSession\": $MAX_SESSIONS,
    \"port\": 5555,
    \"register\": true,
    \"registerCycle\": 5000
  }
}"
